<!DOCTYPE html>
<html>


<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="theme-color" content="#333">
    <title>第16章　例外処理</title>
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8">
    <link rel="stylesheet" href="../assets/css/style.light-blue-500.min.css">
    <link rel="shortcut icon" href="../assets/img/demo/home_icon.png">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="../assets/css/preload.min.css">
    <link rel="stylesheet" href="../assets/css/plugins.min.css">
    <script src="../../cdn.jsdelivr.net/npm/showdown%401.9.0/dist/showdown.min.js"></script>
    <script src="../assets/js/showdown-prettify.min.js"></script>
    <script src="../../cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
    <style>
        li.L0, li.L1, li.L2, li.L3,
        li.L5, li.L6, li.L7, li.L8 {
          list-style-type: decimal !important;
        }
    </style>
</head>

<body style="font-size:1.5rem;">
    <script type="text/javascript" src="header.html"></script>
    <div class="ms-hero-page ms-hero-img-headbg ms-hero-bg-primary mb-6">
        <div class="container">
            <a style="position:absolute; top:0px; left:auto;" href="../main-index.html"><img style="height: 60px;"src="../assets/img/demo/home_icon.png" alt=""></a>
            <div class="text-center">
                <br>
                <br>
                <h1 class="no-m ms-site-title color-white center-block ms-site-title-lg mt-2 animated zoomInDown animation-delay-5" style="margin-top:2rem!important;">第16章　例外処理</h1>
                <p class="lead lead-lg color-white text-center center-block mt-2 mb-4 mw-800 text-uppercase fw-300 animated fadeInUp animation-delay-7" style="margin-top:2rem!important; margin-bottom:4rem!important;">
                    例外処理に関する基本的な考え方について説明します
                </p>
                <a style="margin-top:2rem; font-size:1.3rem;" href="../main-index.html" class="btn btn-raised btn-warning animated fadeInUp animation-delay-10">homepage</a>
                
            </div>
        </div>
    </div>
    <div style="margin: 0 auto; max-width: 1024px;">
        <textarea id="text" style="display:none"># **例外処理**

***

Javaでプログラムを作成した場合、コンパイルの時点でエラーが発生する場合と実行中にエラーが発生する場合があります。

## **1.例外（Exception）とは**
プログラムは予めどういった処理をするのか、という手順を書いたものですが、状況によっては予期しない事象で正しく処理が行えないことがあります。

そのような予期しない状況をJavaでは例外(Exception)と呼んでいます。

&lt;br&gt;

## **2.例外の種類**
**(1)例外の種類**

Javaで発生する例外は以下のようになります。

**・Error**

システム上重大な回復不能な異常な事象。そもそも回復不能な重大な状況なので、プログラム側ではほとんど対応のしようがありません。（例：メモリ不足、スタックオーバーフロー、その他JRE自体に問題があり、JRE自体が停止する事象)

&lt;br&gt;

**・RuntimeException**

実行時に起こった例外で必ずしも対処しなくても良い事象。例外処理を書くか書かないかは状況によります。プログラムのバグの可能性も多いので、プログラムを修正することが正しい対応となる場合もあります。

例えば、以下のような場合が該当します。

Stringの数字をintの整数に変換しようとしたがそもそも数字ではなかった(NumberFormatException)
```
		String s = &quot;abc&quot;;
		int j = Integer.parseInt(s);
```

インスタンスがある前提でプログラムは書かれているのに存在しなかった(NullPointerException)

&lt;br&gt;

**・Exception**

上記以外の例外。例外の処理を行う必要がある。

Exceptionは、例外処理を書かなければ、コンパイルに通らないので例外処理の記述を強制されます。これにより、想定外の状況をなるべく無くすことが可能となります。

Exceptionの代表的な例としては、ファイルを開こうとしたが対象のファイルが存在しなかった(FileNotFoundException)、などです。

&lt;br&gt;

**(2)checked例外とunchecked例外**

checked例外は、コンパイル時にチェックされる例外。
上記の`Exception`クラス以下の例外

unchecked例外は、コンパイル時にチェックされない例外。
上記の`Error`クラスと`RuntimeException`クラス以下の例外


&lt;a href=&quot;https://docs.oracle.com/javame/config/cdc/ref-impl/cdc1.1.2/jsr218/ja/java/lang/package-tree.html&quot; target=&quot;_blank&quot;&gt;クラス階層を参照ください。&lt;/a&gt;


#### **例1**
[ArithmeticExceptionTest.java]

```
package JException

public class ArithmeticExceptionTest {
	public static void main(String[] args) {
		System.out.println(&quot; Exception in thread \&quot;main\&quot;&quot;);

		for (int i = 10; i &gt; 0; i--) {
			System.out.print(&quot; &quot; + (i / (i - 1)));
			if (i % 5 == 0)
				System.out.println();
		}
	}
}
```
#### **実行結果**
Exception in thread &quot;main&quot;&lt;br&gt;
 1&lt;br&gt;
 1 1 1 1 1&lt;br&gt;
 1 1 2java.lang.ArithmeticException: / by zero&lt;br&gt;
	at Error.ArithmeticException.main(ArithmeticException.java:8)

&lt;br&gt;

#### **例2**
[Checked_UnCheckedExceptionDemo.java]

```
package JException

public class Checked_UnCheckedExceptionDemo {

	public static void main(String[] args) {
		uncheckedFunction1();
		//実行中、uncheck exception発生、実行中止
		uncheckedFunction2();
		try {
			checkFunction();
		}catch (MyCheckException e){
			throw new RuntimeException(e);
		}
	}

	public static void uncheckedFunction1() {
		//メソッドの中に、exception発生、必ず処理。try-catch Or throw
		System.out.println(&quot;uncheckedFunction1()が実行された&quot;);
		throw new NullPointerException();
	}

	public static void uncheckedFunction2() throws IllegalArgumentException {
		System.out.println(&quot;uncheckedFunction2()が実行された&quot;);
		// 呼び出し時、catchしない
	}

	public static void checkFunction() throws MyCheckException {
		System.out.println(&quot;invoke test3&quot;);
		//check exception発生、必ず処理。try-catch
	}
}

class MyCheckException extends Exception {
		public MyCheckException() {
			super();
		}
}
```
#### **実行結果**
uncheckedFunction1()が実行された&lt;br&gt;
Exception in thread &quot;main&quot; java.lang.NullPointerException&lt;br&gt;
	at Error.Checked_UnCheckedExceptionDemo.uncheckedFunction1(Checked_UnCheckedExceptionDemo.java:19)&lt;br&gt;
	at Error.Checked_UnCheckedExceptionDemo.main(Checked_UnCheckedExceptionDemo.java:6)

&lt;br&gt;

## **3.例外の処理方法**
例外処理は以下の2つの方法があります。

* 自分で例外を処理する
* 自分では処理せず、例外処理を呼び出し元のクラスにスルーする

### **3-1.自分で例外を処理する**

基本的な書式は次の通りです。

&lt;pre&gt;&lt;code&gt;try{
例外が発生しているかどうか調べる文1;
例外が発生しているかどうか調べる文2;
  ...
}
catch (例外クラス1 変数名1){
例外クラス1の例外が発生した時に行う文;
  ...
}
catch (例外クラス2 変数名2){
例外クラス2の例外が発生した時に行う文;
  ...
}
&lt;/code&gt;&lt;/pre&gt;

必ず実行する処理の記述(try..catch..**finally**)

&lt;pre&gt;&lt;code&gt;try{
例外が発生しているかどうか調べる文1;
例外が発生しているかどうか調べる文2;
  ...
}
catch (例外クラス1 変数名1){
例外クラス1の例外が発生した時に行う文;
  ...
}
catch (例外クラス2 変数名2){
例外クラス2の例外が発生した時に行う文;
  ...
}
finally {
例外が発生するしないに関わらず実行する文;
  ...
}
&lt;/code&gt;&lt;/pre&gt;
finally中の処理は、try文の中で例外が発生してもしなくても**必ず**実行されます。

その為、**必ず**行っておきたい処理がある場合にはfinallyブロックを用意してブロック内に記述するようにして下さい。

&lt;br&gt;

### **3-2.例外を呼び出し元へスルーする**
呼び出し元へスルーする場合は、メソッドのシグニチャにthrows句を記述します。

```
public void read() throws FileNotFoundException, IOException {
	//メソッド内容
}
```

***

&gt; **練習**
&gt;&gt; **問題**[JEx16_1.java]

上記例1の例外を処理ください。</textarea>
        <p id="output">content</p>
    </div>
    <div class="text-center">
        <a style="margin-top:2rem; margin-bottom:3rem; font-size:2rem; width:90px;" href="#" onClick="javascript:history.back(-1);" class="btn btn-raised btn-info animated fadeInUp animation-delay-10">戻る</a>
    </div>
    <script>
    showdown.setOption('omitExtraWLInCodeBlocks', 'true');
    showdown.setOption('ghCodeBlocks', 'true');
    var converter = new showdown.Converter({ extensions: ['prettify'] });
    html = converter.makeHtml(document.getElementById('text').value);
    document.getElementById('output').innerHTML = html;
    </script>
</body>


</html>